language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm prune

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/