name: PR PreCheck
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Validate PR
        uses: actions/github-script@v9
        with:
          script: |
            const preCheck = await import(`${github.workspace}/scripts/workflow.preCheck.js`);

            await preCheck.start({
              isFreezeActive: '${{ vars.RELEASE_FREEZE_ACTIVE }}' === 'true',
              LABEL_CODE_FREEZE: 'bot:code-freeze',
              LABEL_BREAKING_POTENTIAL: 'bot:breaking-potential',
              LABEL_NEEDS_CLEANUP: 'bot:needs-cleanup',
              LABEL_NEEDS_MAINTAINER: 'bot:needs-maintainer',
              LABEL_CONFIRMED: 'bot:contributor-confirmed',
              LABEL_UNCONFIRMED: 'bot:contributor-unconfirmed',
              LABEL_PRECHECKS_PASS: 'bot:ready-for-testing',
              LABEL_PRECHECKS_BYPASS: 'bot:maintainer-bypass',
              LABEL_SEC: 'bot:needs-sec'
            }, {
              github,
              context,
              core,
            });
