name: Build
on:
  pull_request:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  Gatekeeper:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Trusted configuration
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Force our main/base branch
          path: trusted-gatekeeper
          sparse-checkout: |
            .github
            scripts
          sparse-checkout-cone-mode: false

      - name: Validate PR
        uses: actions/github-script@v9
        with:
          script: |
            const { pathToFileURL } = require('url');

            // 1. Build the absolute system path string
            const absolutePath = `${process.env.GITHUB_WORKSPACE}/trusted-gatekeeper/scripts/workflow.preCheck.js`;
            console.log('1', process.env.GITHUB_WORKSPACE);
            console.log('2', process.pwd());
            // 2. Convert it to a valid file:// URL format (Node ESM Requirement)
            const scriptUrl = pathToFileURL(absolutePath).href;

            // const scriptPath = `${process.env.GITHUB_WORKSPACE}/trusted-gatekeeper/scripts/workflow.preCheck.js`;
            const module = await import(scriptUrl);
            const startFn = module.start || module.default;

            await startFn({
              LABEL_NEEDS_CLEANUP: 'bot:needs-cleanup',
              LABEL_NEEDS_MAINTAINER: 'bot:needs-maintainer',
              LABEL_PRECHECKS_PASS: 'bot:ready-for-testing'
            }, {
              github,
              context,
              core,
            });

      - name: Lint
        uses: actions/github-script@v9
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/trusted-gatekeeper/scripts/workflow.commitLint.js`;
            const module = await import(scriptPath);
            const workflowCommitLint = module.workflowCommitLint || module.default;

            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const { resultsArray, resultsString } = workflowCommitLint(commits);

            if (resultsArray.length) {
              core.setFailed(resultsString);
            }
